In [8]:
import tensorflow as tf

class SentCNN:
    def __init_(self, input_dim, hidden_dim, max_sent_len, class_num):
        self.input_x = tf.placeholder(tf.float32, [None, max_sent_len, input_dim], name="input_x")
        self.input_y = tf.placeholder(tf.float32, [None, class_num], name="input_y")
        num_filters = 256
        kernel_size = 5
        conv_input = tf.layers.conv1d(inputs, num_filters, kernel_size,strides=1, padding='valid',name='conv2')
        feature_map = tf.relu(conv_input) # [batchsize, conv_feats, filters]
        self.pooled_feat = tf.reduce_max(feature_map, 1)
        classifier = tf.layers.Dense(3, activation= tf.nn.relu, trainable=True)
        self.pred_scores = tf.nn.softmax(classifier(self.pooled_feat), axis=1)
        self.loss = 

In [9]:
ipt_x = tf.placeholder(tf.float32, [None, 10, 5], name="input_x")
import numpy as np
rm = np.random.rand(3, 10, 5)
m = tf.reduce_max(ipt_x, 2)
d = tf.layers.Dense(3, activation= tf.nn.relu, trainable=True)
sess = tf.Session()

In [10]:
with sess.as_default():
    tf.global_variables_initializer().run()

In [11]:
sess.run(m, feed_dict={ipt_x:rm})

array([[0.5441906 , 0.8318912 , 0.8160324 , 0.8752522 , 0.9409457 ,
        0.8530572 , 0.72460777, 0.9465967 , 0.9013317 , 0.78937036],
       [0.9271213 , 0.93437266, 0.46446687, 0.37157094, 0.8782632 ,
        0.64659   , 0.97321266, 0.88701713, 0.915626  , 0.96424925],
       [0.87826717, 0.9834535 , 0.86942923, 0.5453663 , 0.7001107 ,
        0.9066905 , 0.7738614 , 0.8551436 , 0.93513906, 0.97188175]],
      dtype=float32)

In [12]:
dd = d(m)

In [13]:
with sess.as_default():
    tf.global_variables_initializer().run()

In [14]:
sess.run(dd, feed_dict={ipt_x:rm})

array([[0.       , 0.       , 1.4736935],
       [0.       , 0.       , 1.5519841],
       [0.       , 0.       , 1.9040263]], dtype=float32)

In [18]:
sess.run(tf.nn.softmax(dd, axis=1), feed_dict={ipt_x:rm})

array([[0.15710106, 0.15710106, 0.68579787],
       [0.14879121, 0.14879121, 0.7024176 ],
       [0.11477277, 0.11477277, 0.77045447]], dtype=float32)

In [21]:
l = tf.constant([1,0,0],(3,3))

TypeError: Cannot convert value (3, 3) to a TensorFlow DType.