In [4]:
import tensorflow as tf

class SentCNN:
    def __init_(self, input_dim, hidden_dim, max_sent_len, class_num):
        self.input_x = tf.placeholder(tf.float32, [None, max_sent_len, input_dim], name="input_x")
        self.input_y = tf.placeholder(tf.float32, [None, class_num], name="input_y")
        num_filters = 256
        kernel_size = 5
        conv_input = tf.layers.conv1d(inputs, num_filters, kernel_size,strides=1, padding='valid',name='conv2')
        feature_map = tf.relu(conv_input) # [batchsize, conv_feats, filters]
        self.pooled_feat = tf.reduce_max(feature_map, 1)
        classifier = tf.layers.Dense(3, activation= tf.nn.relu, trainable=True)
        self.pred_scores = classifier(self.pooled_feat)
        self.loss = tf.losses.softmax_cross_entropy(
    self.input_y,
    self.pred_scores,
    weights=1.0,
    label_smoothing=0,
    scope=None,
    loss_collection=tf.GraphKeys.LOSSES 
)

In [5]:
ipt_x = tf.placeholder(tf.float32, [None, 10, 5], name="input_x")
import numpy as np
rm = np.random.rand(3, 10, 5)
m = tf.reduce_max(ipt_x, 2)
d = tf.layers.Dense(3, activation= tf.nn.relu, trainable=True)
sess = tf.Session()

In [6]:
with sess.as_default():
    tf.global_variables_initializer().run()

In [7]:
sess.run(m, feed_dict={ipt_x:rm})

array([[0.80458635, 0.77087307, 0.72253996, 0.65073276, 0.7551314 ,
        0.83436346, 0.89131194, 0.6152131 , 0.9187489 , 0.9580402 ],
       [0.8392782 , 0.96472466, 0.9425624 , 0.92444646, 0.92648566,
        0.7616283 , 0.98676044, 0.99242675, 0.8579236 , 0.929951  ],
       [0.90843916, 0.908455  , 0.88483137, 0.94633716, 0.8346903 ,
        0.9009754 , 0.69429547, 0.8504787 , 0.6619101 , 0.552041  ]],
      dtype=float32)

In [8]:
dd = d(m)

W0731 16:31:33.525002 4601943488 deprecation.py:506] From /Users/lumenglong/anaconda3/envs/TF/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [9]:
with sess.as_default():
    tf.global_variables_initializer().run()

In [10]:
sess.run(dd, feed_dict={ipt_x:rm})

array([[1.6946235, 0.660918 , 0.       ],
       [1.8199023, 0.7351316, 0.       ],
       [1.7186108, 0.3424124, 0.       ]], dtype=float32)

In [11]:
sess.run(, feed_dict={ipt_x:rm})

array([[0.64962274, 0.23106207, 0.11931515],
       [0.6666574 , 0.22531639, 0.10802621],
       [0.69839627, 0.17637075, 0.125233  ]], dtype=float32)

In [20]:
l = tf.constant([[1,0,0],[0,1,0], [1,0,0]])

In [30]:
pred = tf.nn.softmax(dd, axis=1)
a_pred = sess.run(pred, feed_dict={ipt_x:rm})

In [28]:
from tensorflow.losses import Reduction
loss = tf.losses.softmax_cross_entropy(
    l,
    dd,
    weights=1.0,
    label_smoothing=0,
    scope=None,
    loss_collection=tf.GraphKeys.LOSSES 
)

In [29]:
sess.run(loss, feed_dict={ipt_x:rm})

0.7601939

In [34]:
a = np.log(a_pred)
print(a)

[[-0.4313635  -1.4650689  -2.1259868 ]
 [-0.405479   -1.4902496  -2.2253814 ]
 [-0.35896862 -1.7351669  -2.0775793 ]]


In [35]:
a[0][0]+a[1][1]+a[2][0]

-2.2805817